pcs_teams = {
    "Beyond_Gaming",
    "CTBC_Flying_Oyster",
    "Deep_Cross_Gaming",
    "Dewish_Team",
    "Frank_Esports",
    "HELL_PIGS",
    "Impunity",
    "J_Team",
    "PSG_Talon",
    "West_Point_Esports_Philippines"
}

team_conversion = {
    "psg" : 'PSG_Talon',
    "dcg" : 'Deep_Cross_Gaming'
}


pcs_players = {
    'PSG_Talon': ['Azhi', 'JunJia', 'Maple_(Huang_Yi-Tang)', 'Wako', 'Woody'], 
    'Beyond_Gaming': ['LIKAI', 'Kongyue', '1116', 'Betty', 'Keres'], 
    'J_Team': ['Driver', 'Lauva', 'Minji', 'Bruce', 'Enso'], 
    'Dewish_Team': ['JP6RU8', 'WSL', 'Xiaotu', 'Pepero', 'EnHoa'], 
    'West_Point_Esports_Philippines': ['Relhia', '665', 'NuL1', 'Prage', 'Cha'], 
    'Deep_Cross_Gaming': ['Hanabi_(Su_Chia-Hsiang)', 'Hana', 'Mission', 'Cryscata', 'Orca_(Kuo_Cheng-Han)'], 
    'CTBC_Flying_Oyster': ['Rest', 'Gemini', 'JimieN', 'Shunn', 'ShiauC'], 
    'Impunity': ['LJW', 'Arashi', 'Shera', 'Blaze_(Jia_Xiang)', 'Felia', 'Smerv'], 
    'Frank_Esports': ['Solokill', 'KennyChan', 'Pretender', 'MnM_(Wong_Ka_Chun)', 'Kaiwing'], 
    'HELL_PIGS': ['Taco_(Fan_Zhao-Fu)', 'Godtone', 'Adiogs', 'Tide_(Hsieh_Yu-Che)', 'IC8']
}

player_name_conversion = {
    'kennychan': 'KennyChan',
    'rest': 'Rest',
    'prage': 'Prage',
    'kongyue': 'Kongyue',
    'wako': 'Wako',
    'tide': 'Tide_(Hsieh_Yu-Che)',
    'keres': 'Keres',
    'blaze': 'Blaze_(Jia_Xiang)',
    'maple': 'Maple_(Huang_Yi-Tang)',
    'orca': 'Orca_(Kuo_Cheng-Han)',
    'enhoa': 'EnHoa',
    'betty': 'Betty',
    'junjia': 'JunJia',
    'jimien': 'JimieN',
    '1116': '1116',
    'xiaotu': 'Xiaotu',
    'shera': 'Shera',
    'kaiwing': 'Kaiwing',
    'wsl': 'WSL',
    'hanabi': 'Hanabi_(Su_Chia-Hsiang)',
    '665': '665',
    'mnm': 'MnM_(Wong_Ka_Chun)',
    'ljw': 'LJW',
    'nul1': 'NuL1',
    'hana': 'Hana',
    'smerv': 'Smerv',
    'taco': 'Taco_(Fan_Zhao-Fu)',
    'ic8': 'IC8',
    'woody': 'Woody',
    'driver': 'Driver',
    'solokill': 'Solokill',
    'godtone': 'Godtone',
    'pepero': 'Pepero',
    'gemini': 'Gemini',
    'arashi': 'Arashi',
    'felia': 'Felia',
    'bruce': 'Bruce',
    'shunn': 'Shunn',
    'likai': 'LIKAI',
    'lauva': 'Lauva',
    'jp6ru8': 'JP6RU8',
    'enso': 'Enso',
    'mission': 'Mission',
    'minji': 'Minji',
    'cha': 'Cha',
    'cryscata': 'Cryscata',
    'pretender': 'Pretender',
    'relhia': 'Relhia',
    'shiauc': 'ShiauC',
    'azhi': 'Azhi',
    'adiogs': 'Adiogs'
}